workspace:
  base: /drone
  path: server/apps/files_primary_s3

branches: [ master, release, release/* ]

pipeline:
  install-fed-server:
    image: owncloudci/core
    pull: true
    version: ${FEDERATION_OC_VERSION}
    core_path: /drone/fed-server
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  configure-federation-server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /drone/fed-server
      - php occ a:l
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0
      - php occ config:list
      - echo "export TEST_SERVER_FED_URL=http://federated" > /drone/saved-settings.sh
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  fix-permissions-federation-server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /drone/fed-server -R
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  composer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COMPOSER_HOME=/drone/server/apps/files_primary_s3/.cache/composer
    commands:
      - composer install -n --no-progress

  prepare-app-config:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - mkdir -p /drone/server/config
      - cp tests/drone/${STORAGE}${STORAGE_CONFIG_SUFFIX}.config.php /drone/server/config

  install-core:
    image: owncloudci/core
    pull: true
    db_type: ${DB_TYPE}
    db_host: ${DB_HOST}
    git_reference: ${CORE_BRANCH}
    environment:
      - COMPOSER_HOME=/drone/server/apps/files_primary_s3/.cache/composer
      - NPM_CONFIG_CACHE=/drone/server/apps/files_primary_s3/.cache/npm
      - YARN_CACHE_FOLDER=/drone/server/apps/files_primary_s3/.cache/yarn
      - bower_storage__packages=/drone/server/apps/files_primary_s3/.cache/bower

  php-cs-fixer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      -  vendor/bin/php-cs-fixer fix -v --diff --dry-run --allow-risky yes
    when:
      matrix:
        TEST_SUITE: phpunit

  prepare-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - STORAGE=${STORAGE}
    commands:
      - cd /drone/server
      - php ./occ a:l
      - php ./occ a:e files_primary_s3
      - php ./occ a:l

  prepare-bucket-scality:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wait-for-it scality:8000
      - cd /drone/server
      - php ./occ s3:create-bucket owncloud --accept-warning
      - for I in $(seq 1 9); do php ./occ s3:create-bucket  owncloud$I --accept-warning; done
    when:
      matrix:
        STORAGE: scality

  prepare-bucket-ceph:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wait-for-it ceph:80
      - cd /drone/server
      - php ./occ s3:create-bucket OWNCLOUD --accept-warning
    when:
      matrix:
        STORAGE: ceph

  test-scality:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wait-for-it scality:8000
      - cd /drone/server
      - php ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest.xml
    when:
      matrix:
        TEST_SUITE: phpunit
        STORAGE: scality

  test-ceph:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wait-for-it ceph:80
      - cd /drone/server
      - php ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest.xml
    when:
      matrix:
        TEST_SUITE: phpunit
        STORAGE: ceph

  configure-server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /drone/server
      - php occ a:l
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0
      - php occ config:list
      - chown -R www-data. /drone/server
    when:
      matrix:
        PREPARE_ACCEPTANCE: true

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
     - tail -f /drone/server/data/owncloud.log
    when:
      matrix:
        OWNCLOUD_LOG: true

  federated-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
     - tail -f /drone/fed-server/data/owncloud.log
    when:
      matrix:
        OWNCLOUD_LOG: true
        USE_FEDERATED_SERVER: true

  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://server/
      - OC_TEST_ON_OBJECTSTORE=1
      - BEHAT_FILTER_TAGS=~@app-required&&~@skip&&~@skipOnStorage:${STORAGE}
      - DIVIDE_INTO_NUM_PARTS=5
      - RUN_PART=${PART}
    commands:
      - touch /drone/saved-settings.sh
      - . /drone/saved-settings.sh
      - cd /drone/server
      - chmod +x ./tests/drone/test-acceptance.sh
      - chmod +x ./tests/acceptance/run.sh
      - ./tests/drone/test-acceptance.sh
    when:
      matrix:
        TEST_SUITE: api

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_SERVER_URL=http://server
      - PLATFORM=Linux
      - MAILHOG_HOST=email
      - DIVIDE_INTO_NUM_PARTS=8
      - RUN_PART=${PART}
    commands:
      - touch /drone/saved-settings.sh
      - . /drone/saved-settings.sh
      - cd /drone/server/tests/acceptance
      - chmod 777 /drone/server/tests/acceptance/filesForUpload -R
      - chmod +x run.sh
      - ./run.sh --remote --type webUI --tags "~@app-required&&~@skip&&~@skipOnStorage:${STORAGE}"
    when:
      matrix:
        TEST_SUITE: selenium

  print-log:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cat /drone/server/data/owncloud.log
    when:
      status:  [ failure ]
      matrix:
        TEST_SUITE: phpunit

  rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - .cache
    when:
      local: false
      event: [ push ]
      branch: [ master ]
      matrix:
        REBUILT_CACHE: true

  flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]
      branch: [ master ]
      matrix:
        FLUSH_CACHE: true

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  scality:
    image: owncloudci/scality-s3server
    pull: true
    environment:
      - HOST_NAME=scality
    when:
      matrix:
        STORAGE: scality

  ceph:
    image: owncloudci/ceph:tag-build-master-jewel-ubuntu-16.04
    pull: true
    environment:
      - NETWORK_AUTO_DETECT=4
      - RGW_NAME=ceph
      - CEPH_DEMO_UID=owncloud
      - CEPH_DEMO_ACCESS_KEY=owncloud123456
      - CEPH_DEMO_SECRET_KEY=secret123456
    when:
      matrix:
        STORAGE: ceph

  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/drone/server
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D", "FOREGROUND" ]
    when:
      matrix:
        USE_SERVER: true

  federated:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/drone/fed-server
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D", "FOREGROUND" ]
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: selenium

  mysql:
    image: mysql:5.7
    pull: true
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_HOST: mysql

  email:
    image: mailhog/mailhog
    pull: true
    when:
      matrix:
        TEST_SUITE: selenium


matrix:
  include:
  # unit tests
#    # 5.6
#    - STORAGE: ceph
#      PHP_VERSION: 5.6
#      TEST_SUITE: phpunit
#      CORE_BRANCH: stable10
#
#    - STORAGE: scality
#      PHP_VERSION: 5.6
#      TEST_SUITE: phpunit
#      CORE_BRANCH: stable10
#
#    # 7.0
#    - STORAGE: ceph
#      PHP_VERSION: 7.0
#      TEST_SUITE: phpunit
#      CORE_BRANCH: stable10
#
#    - STORAGE: scality
#      PHP_VERSION: 7.0
#      TEST_SUITE: phpunit
#      CORE_BRANCH: stable10

    # 7.1
    - STORAGE: ceph
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10
      FLUSH_CACHE: true
      REBUILT_CACHE: true

    - STORAGE: scality
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10

    # 7.2
    - STORAGE: ceph
      PHP_VERSION: 7.2
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10

    - STORAGE: scality
      PHP_VERSION: 7.2
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10

    - STORAGE: scality
      STORAGE_CONFIG_SUFFIX: .multibucket
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10

  # 7.1
    - STORAGE: ceph
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: master

    - STORAGE: scality
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: master

    - STORAGE: scality
      STORAGE_CONFIG_SUFFIX: .multibucket
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: master

  # 7.2
    - STORAGE: ceph
      PHP_VERSION: 7.2
      TEST_SUITE: phpunit
      CORE_BRANCH: master

    - STORAGE: scality
      PHP_VERSION: 7.2
      TEST_SUITE: phpunit
      CORE_BRANCH: master

  # acceptance tests
    # UI stable10
    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 1

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 2

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 3

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 4

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 5

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 6

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 7

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 8

    # UI master
    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 1

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 2

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 3

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 4

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 5

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 6

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 7

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 8

    # API stable10
    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 1

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 2

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 3

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 4

    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-stable10-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 5

    # API master
    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 1

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 2

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 3

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 4

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph
      OWNCLOUD_LOG: true
      PART: 5
