workspace:
  base: /drone
  path: server/apps/files_primary_s3

branches: [ master, release, release/* ]

pipeline:
  restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  composer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COMPOSER_HOME=/drone/server/apps/files_primary_s3/.cache/composer
    commands:
      - composer install -n --no-progress

  install-core:
    image: owncloudci/core
    pull: true
    db_type: ${DB_TYPE}
    db_host: ${DB_HOST}
    git_reference: ${CORE_BRANCH}
    environment:
      - COMPOSER_HOME=/drone/server/apps/files_primary_s3/.cache/composer
      - NPM_CONFIG_CACHE=/drone/server/apps/files_primary_s3/.cache/npm
      - YARN_CACHE_FOLDER=/drone/server/apps/files_primary_s3/.cache/yarn
      - bower_storage__packages=/drone/server/apps/files_primary_s3/.cache/bower

  php-cs-fixer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      -  vendor/bin/php-cs-fixer fix -v --diff --dry-run --allow-risky yes
    when:
      matrix:
        TEST_SUITE: phpunit

  prepare-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - STORAGE=${STORAGE}
    commands:
      - cp tests/drone/$${STORAGE}.config.php /drone/server/config
      - cd /drone/server
      - php ./occ a:l
      - php ./occ a:e files_primary_s3
      - php ./occ a:l

  prepare-bucket-scality:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wait-for-it scality:8000
      - cd /drone/server
      - php ./occ s3:create-bucket owncloud --accept-warning
    when:
      matrix:
        STORAGE: scality

  prepare-bucket-ceph:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wait-for-it ceph:80
      - cd /drone/server
      - php ./occ s3:create-bucket OWNCLOUD --accept-warning
    when:
      matrix:
        STORAGE: ceph

  test-scality:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wait-for-it scality:8000
      - cd /drone/server
      - php ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest.xml
    when:
      matrix:
        TEST_SUITE: phpunit
        STORAGE: scality

  test-ceph:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wait-for-it ceph:80
      - cd /drone/server
      - php ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest.xml
    when:
      matrix:
        TEST_SUITE: phpunit
        STORAGE: ceph

  configure-server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps
      - git clone https://github.com/owncloud/testing.git
      - cd /drone/server
      - php occ a:l
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0
      - php occ config:list
      - chown -R www-data. /drone/server
    when:
      matrix:
        PREPARE_ACCEPTANCE: true


  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://server/
      - TEST_SERVER_FED_URL=http://federated/
      - OC_TEST_ON_OBJECTSTORE=1
      - BEHAT_FILTER_TAGS=~@app-required&&~@skip&&~@masterkey_encryption
    commands:
    - cd /drone/server
    - chmod +x ./tests/drone/test-api-acceptance.sh
    - chmod +x ./tests/acceptance/run.sh
    - ./tests/drone/test-api-acceptance.sh
    when:
      matrix:
        TEST_SUITE: api

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome
      - SELENIUM_HOST=selenium
      - SRV_HOST_NAME=server
      - SRV_HOST_PORT=80
      - REMOTE_FED_SRV_HOST_NAME=federated
      - REMOTE_FED_SRV_HOST_PORT=80
      - SKELETON_DIR=/drone/server/tests/acceptance/webUISkeleton
      - SELENIUM_PORT=4444
      - PLATFORM=Linux
      - MAILHOG_HOST=email
    commands:
      - cd /drone/server
      - chmod 777 /drone/server/tests/acceptance/filesForUpload -R
      - bash tests/travis/start_ui_tests.sh --tags "~@app-required&&~@skip" --remote --all-suites
    when:
      matrix:
        TEST_SUITE: selenium


  print-log:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cat /drone/server/data/owncloud.log
    when:
      status:  [ failure ]

  rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - .cache
    when:
      local: false
      event: [ push ]
      branch: [ master ]
      matrix:
        REBUILT_CACHE: true

  flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]
      branch: [ master ]
      matrix:
        FLUSH_CACHE: true

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  scality:
    image: owncloudci/scality-s3server
    pull: true
    environment:
      - HOST_NAME=scality
    when:
      matrix:
        STORAGE: scality

  ceph:
    image: ceph/daemon:v3.0.7-stable-3.0-luminous-centos-7
    pull: true
    environment:
      - NETWORK_AUTO_DETECT=4
      - CEPH_DAEMON=demo
      - CEPH_DEMO_UID=owncloud
      - CEPH_DEMO_ACCESS_KEY=owncloud123456
      - CEPH_DEMO_SECRET_KEY=secret123456
      - DEBUG=verbose
      - RGW_CIVETWEB_PORT=80
    when:
      matrix:
        STORAGE: ceph

  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/drone/server
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D", "FOREGROUND" ]
    when:
      matrix:
        USE_SERVER: true

  federated:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/drone/server
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D", "FOREGROUND" ]
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: selenium

  mysql:
    image: mysql:5.7
    pull: true
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_HOST: mysql

  email:
    image: mailhog/mailhog
    pull: true
    when:
      matrix:
        TEST_SUITE: selenium


matrix:
  include:
  # unit tests
#    # 5.6
#    - STORAGE: ceph
#      PHP_VERSION: 5.6
#      TEST_SUITE: phpunit
#      CORE_BRANCH: stable10
#
#    - STORAGE: scality
#      PHP_VERSION: 5.6
#      TEST_SUITE: phpunit
#      CORE_BRANCH: stable10
#
#    # 7.0
#    - STORAGE: ceph
#      PHP_VERSION: 7.0
#      TEST_SUITE: phpunit
#      CORE_BRANCH: stable10
#
#    - STORAGE: scality
#      PHP_VERSION: 7.0
#      TEST_SUITE: phpunit
#      CORE_BRANCH: stable10

    # 7.1
    - STORAGE: ceph
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10
      FLUSH_CACHE: true
      REBUILT_CACHE: true

    - STORAGE: scality
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10

    # 7.2
    - STORAGE: ceph
      PHP_VERSION: 7.2
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10

    - STORAGE: scality
      PHP_VERSION: 7.2
      TEST_SUITE: phpunit
      CORE_BRANCH: stable10
    # 7.1
    - STORAGE: ceph
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: master

    - STORAGE: scality
      PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      CORE_BRANCH: master

    # 7.2
    - STORAGE: ceph
      PHP_VERSION: 7.2
      TEST_SUITE: phpunit
      CORE_BRANCH: master

    - STORAGE: scality
      PHP_VERSION: 7.2
      TEST_SUITE: phpunit
      CORE_BRANCH: master

  # acceptance tests
    # UI
    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      TEST_SUITE: selenium
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph

    # API
    - PHP_VERSION: 7.1
      CORE_BRANCH: stable10
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph

    - PHP_VERSION: 7.1
      CORE_BRANCH: master
      PREPARE_ACCEPTANCE: true
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      TEST_SUITE: api
      DB_TYPE: mysql
      DB_HOST: mysql
      STORAGE: ceph