---
kind: pipeline
type: docker
name: coding-standard-php7.0

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_primary_s3

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.0
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phpunit-scality-php7.1-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_primary_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_primary_s3
    git_reference: timing-in-VersioningTest

- name: install-app-files_primary_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install

- name: setup-server-files_primary_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-scality
  pull: always
  image: owncloudci/php:7.0
  commands:
  - wait-for-it -t 60 scality:8000
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/scality.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server
  - php occ s3:create-bucket owncloud --accept-warning
  - for I in $(seq 1 9); do php ./occ s3:create-bucket  owncloud$I --accept-warning; done

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit

services:
- name: scality
  pull: always
  image: owncloudci/scality-s3server
  environment:
    HOST_NAME: scality

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0

---
kind: pipeline
type: docker
name: phpunit-scality-multibucket-php7.1-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_primary_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_primary_s3
    git_reference: timing-in-VersioningTest

- name: install-app-files_primary_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install

- name: setup-server-files_primary_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-scality
  pull: always
  image: owncloudci/php:7.0
  commands:
  - wait-for-it -t 60 scality:8000
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/scality.multibucket.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server
  - php occ s3:create-bucket owncloud --accept-warning
  - for I in $(seq 1 9); do php ./occ s3:create-bucket  owncloud$I --accept-warning; done

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit

services:
- name: scality
  pull: always
  image: owncloudci/scality-s3server
  environment:
    HOST_NAME: scality

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0

---
kind: pipeline
type: docker
name: phpunit-ceph-php7.1-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_primary_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_primary_s3
    git_reference: timing-in-VersioningTest

- name: install-app-files_primary_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install

- name: setup-server-files_primary_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-ceph
  pull: always
  image: owncloudci/php:7.0
  commands:
  - wait-for-it -t 60 ceph:80
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/ceph.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server
  - ./apps/files_primary_s3/tests/drone/create-bucket.sh

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit

services:
- name: ceph
  pull: always
  image: owncloudci/ceph:tag-build-master-jewel-ubuntu-16.04
  environment:
    CEPH_DEMO_ACCESS_KEY: owncloud123456
    CEPH_DEMO_SECRET_KEY: secret123456
    CEPH_DEMO_UID: owncloud
    NETWORK_AUTO_DETECT: 4
    RGW_NAME: ceph

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.0

---
kind: pipeline
type: docker
name: chat-notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify-rocketchat
  pull: always
  image: plugins/slack:1
  settings:
    channel: builds
    webhook:
      from_secret: private_rocketchat

trigger:
  ref:
  - refs/tags/**
  - refs/heads/master

depends_on:
- phpunit-scality-php7.1-sqlite
- phpunit-scality-multibucket-php7.1-sqlite
- phpunit-ceph-php7.1-sqlite

...
