workspace:
  base: /drone
  path: server/apps/files_primary_s3

branches: [ master ]

pipeline:
  restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  install-server:
    image: owncloudci/core
    pull: true
    git_reference: ${CORE_BRANCH}

  composer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COMPOSER_CACHE_DIR=composer
    commands:
      - composer install -n --no-progress

  prepare-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /drone/server
      - rm -rf tests/lib/Files/ObjectStore/SwiftTest.php
      - php ./occ a:l
      - php ./occ a:e files_primary_s3
      - php ./occ a:l

  test-scality:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - RUN_OBJECTSTORE_TESTS=1
    commands:
      - cp tests/drone/scality.config.php /drone/server/config
      - wait-for-it scality:8000
      - cd /drone/server
      - php ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest.xml
    when:
      matrix:
        STORAGE: scality

  test-ceph:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - RUN_OBJECTSTORE_TESTS=1
    commands:
      - cp tests/drone/ceph.config.php /drone/server/config
      - wait-for-it ceph:80
      - cd /drone/server
      - php ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest.xml
    when:
      matrix:
        STORAGE: ceph

  print-log:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cat /drone/server/data/owncloud.log
    when:
      status:  [ failure ]

  rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - composer
      - vendor
    when:
      local: false
      event: [ push ]
      branch: [ master ]

  flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]
      branch: [ master ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: objectstore-team
    when:
      local: false
      status: [ changed, failure ]

services:
  scality:
#    image: scality/s3server:d75a5612
    # own build of scality/s3server which fixes https://github.com/scality/S3/issues/1012
    image: deepdiver/s3server:7.1
    pull: true
    environment:
      - HOST_NAME=scality
    when:
      matrix:
        STORAGE: scality

  ceph:
    image: ceph/demo:tag-build-master-jewel-ubuntu-16.04
    pull: true
    environment:
      - NETWORK_AUTO_DETECT=4
      - RGW_NAME=ceph
      - CEPH_DEMO_UID=owncloud
      - CEPH_DEMO_ACCESS_KEY=owncloud123456
      - CEPH_DEMO_SECRET_KEY=secret123456
    when:
      matrix:
        STORAGE: ceph


matrix:
  include:
#    # 5.6
#    - STORAGE: ceph
#      PHP_VERSION: 5.6
#      CORE_BRANCH: stable10
#    - STORAGE: scality
#      PHP_VERSION: 5.6
#      CORE_BRANCH: stable10
#    # 7.0
#    - STORAGE: ceph
#      PHP_VERSION: 7.0
#      CORE_BRANCH: stable10
#    - STORAGE: scality
#      PHP_VERSION: 7.0
#      CORE_BRANCH: stable10
#    # 7.1
#    - STORAGE: ceph
#      PHP_VERSION: 7.1
#      CORE_BRANCH: stable10
#    - STORAGE: scality
#      PHP_VERSION: 7.1
#      CORE_BRANCH: stable10
#    # 7.2
#    - STORAGE: ceph
#      PHP_VERSION: 7.2
#      CORE_BRANCH: stable10
#    - STORAGE: scality
#      PHP_VERSION: 7.2
#      CORE_BRANCH: stable10
    # 7.1
    - STORAGE: ceph
      PHP_VERSION: 7.1
      CORE_BRANCH: master
    - STORAGE: scality
      PHP_VERSION: 7.1
      CORE_BRANCH: master
    # 7.2
    - STORAGE: ceph
      PHP_VERSION: 7.2
      CORE_BRANCH: master
    - STORAGE: scality
      PHP_VERSION: 7.2
      CORE_BRANCH: master
